# Generated by Django 3.2.5 on 2021-07-07 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hotel'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(auto_created=True, blank=True, default=datetime.date(2021, 7, 7), null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='duracion',
            field=models.PositiveIntegerField(),
        ),
    ]
