# Generated by Django 3.2.5 on 2021-07-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20210707_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='costo_dia',
            field=models.FloatField(default=0, verbose_name='costo diario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_pagar',
            field=models.FloatField(default=0, verbose_name='Monto a pagar'),
        ),
    ]
